
import React, { createContext, useContext, useState, ReactNode, useMemo } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  formatDate: (date: string | Date, options?: Intl.DateTimeFormatOptions) => string;
  formatDateTime: (date: string | Date) => string;
  formatCurrency: (value: number) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.operations': 'Operations',
    'nav.analytics': 'Analytics',
    'nav.inventory': 'Active Stock',
    'nav.clients': 'Clients CRM',
    'nav.thermometer': 'Interest Heatmap',
    'nav.lot_history': 'Lot History',
    'nav.dashboard': 'Dashboard',
    'nav.pipeline': 'Active Links',
    'nav.sales': 'Sales History',
    'nav.financials_admin': 'Net Profit Analysis',
    'nav.financials_seller': 'My Commissions',
    // CRM
    'cli.title': 'Customer Relationship',
    'cli.subtitle': 'Manage your client portfolio and track engagement history.',
    'cli.add': 'Add New Client',
    'cli.search': 'Search name, company or email...',
    'cli.table.client': 'Client / Company',
    'cli.table.contact': 'Contact Info',
    'cli.table.offers': 'Offers',
    'cli.table.total_purchased': 'Purchased',
    'cli.table.status': 'Engagement',
    'cli.kpi.total_clients': 'Total Clients',
    'cli.kpi.active_leads': 'Active Leads',
    'cli.kpi.conversion': 'Conversion',
    'cli.modal.new': 'New Client Registration',
    'cli.modal.edit': 'Edit Client Details',
    'cli.modal.edit_btn': 'Edit Info',
    'cli.label.name': 'Full Name',
    'cli.label.company': 'Company / Office',
    'cli.label.email': 'Email Address',
    'cli.label.phone': 'Phone Number',
    'cli.label.notes': 'Relationship Notes',
    'cli.label.no_notes': 'No observations registered.',
    'cli.label.member_since': 'Client since',
    'cli.label.registered_by': 'Registered by',
    'cli.history.title': 'Link History',
    'cli.history.empty': 'No links generated for this client.',
    'cli.history.filter_all': 'All Links',
    'cli.history.filter_sold': 'Sold',
    'cli.history.filter_active': 'Open',
    'cli.history.search_placeholder': 'Search material or lot...',
    'cli.history.seller_filter': 'All Sellers',
    'cli.status.hot': 'Hot Lead',
    'cli.status.inactive': 'Inactive',
    'cli.select_existing': 'Select from CRM',
    // Dashboard & Analytics
    'dash.title_admin': 'Industry Analytics',
    'dash.title_seller': 'Sales Performance',
    'dash.subtitle_admin': 'Real-time overview of global operations.',
    'dash.subtitle_seller': 'Track your active links and commissions.',
    'dash.kpi.pipeline': 'In Negotiation',
    'dash.kpi.pipeline_desc': 'Potential revenue from active links',
    'dash.kpi.sold': 'Total Sold',
    'dash.kpi.sold_desc': 'Realized revenue',
    'dash.kpi.revenue': 'Total Revenue',
    'dash.kpi.potential_revenue': 'Potential Revenue',
    'dash.kpi.profit': 'Net Profit',
    'dash.kpi.transactions': 'Transactions',
    'dash.kpi.volume': 'Total Volume',
    'dash.kpi.units': 'units',
    'dash.kpi.reserved_links': 'Reserved Links',
    'dash.kpi.reserved_links_desc': 'Offers locked as reserved',
    'dash.kpi.profit_admin': 'Net Profit',
    'dash.kpi.profit_seller': 'Commissions',
    'dash.kpi.profit_desc': 'Based on closed deals',
    'dash.filter.all_sellers': 'All Partners',
    'dash.status.sold': 'Sold',
    'dash.status.expired': 'Expired',
    'dash.status.active': 'Active',
    'dash.records_found': 'records found',
    'dash.recent_transactions': 'Recent Activity',
    'dash.table.status': 'Status',
    'dash.table.stone': 'Material / Lot',
    'dash.table.client': 'Client',
    'dash.table.value': 'Value',
    'dash.table.actions': 'Actions',
    'dash.table.created': 'Date',
    'dash.table.seller': 'Seller',
    'dash.filter.all': 'All Time',
    'dash.filter.week': 'This Week',
    'dash.filter.month': 'This Month',
    'dash.filter.custom': 'Custom Range',
    // Inventory
    'inv.your_inventory': 'Manage your available slabs and batches.',
    'inv.search_placeholder': 'Search lot ID or stone...',
    'inv.filter.all_types': 'All Typologies',
    'inv.filter.all_status': 'All Status',
    'inv.status.available': 'Available',
    'inv.status.reserved': 'Reserved',
    'inv.status.sold_out': 'Sold Out',
    'inv.switch.lots': 'Lots',
    'inv.switch.catalog': 'Catalog',
    'inv.add_typology': 'New Typology',
    'inv.history_title': 'Inventory Archive',
    'inv.history_subtitle': 'History of stones fully sold and transactions closed.',
    'inv.history_empty': 'No lots have been fully sold yet.',
    'inv.add_batch': 'New Batch',
    'inv.no_results': 'No items found.',
    // Cards
    'card.lot': 'Lot',
    'card.floor_price': 'Floor Price',
    'card.direct_link': 'HQ Link',
    'card.delegate': 'Delegate',
    'card.create_offer': 'Create Offer',
    'card.sold': 'Sold',
    'card.reserved': 'Reserved',
    'card.sent': 'Links Sent',
    'card.sent_short': 'Sent',
    'card.avail': 'Avail',
    'card.your_stock': 'Your Stock',
    'card.not_in_showroom': 'Not in your showroom',
    // Units
    'unit.slabs': 'slabs',
    'unit.m2': 'm²',
    // Catalog
    'cat.no_image': 'No Image Available',
    // Common
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.search_placeholder': 'Search client, stone or lot...',
    'common.direct_sale': 'Direct Sale',
    'common.select_placeholder': 'Select...',
    'analytics.desc': 'Detailed financial performance and link metrics.',
    'analytics.export': 'Export CSV',
    // Actions
    'actions.request_reservation': 'Request Reservation',
    'actions.reserve_now': 'Reserve Now',
    'actions.approve': 'Approve',
    'actions.reject': 'Reject',
    // Modals - History & Status (Global)
    'modal.history.title': 'Transaction History',
    'modal.history.sold': 'Sold',
    'modal.history.expired': 'Expired',
    'modal.history.active': 'Active',
    'modal.history.copy': 'Copy Link',
    'modal.history.view': 'View Page',
    'modal.history.displaying': 'Displaying',
    'modal.history.no_links': 'No links generated yet.',
    // Modals - Transactions
    'modal.tx.created': 'Created At',
    'modal.tx.viewed': 'Viewed',
    'modal.tx.finalized': 'Finalized',
    'modal.tx.id': 'ID',
    'modal.tx.sold': 'Sold',
    'modal.tx.active': 'Active',
    'modal.tx.unit_price': 'Unit Price',
    'modal.tx.qty': 'Quantity',
    'modal.tx.total_val': 'Total Value',
    'modal.tx.margin': 'Margin %',
    'modal.tx.est_profit': 'Est. Profit',
    'modal.tx.est_comm': 'Est. Comm',
    'modal.tx.timeline': 'Activity Timeline',
    'modal.tx.open': 'Open Secure View',
    'modal.tx.cancel': 'Revoke Link',
    'modal.tx.finalize': 'Confirm Sale',
    // Modals - Types
    'modal.type.edit_title': 'Edit Typology',
    'modal.type.new_title': 'New Typology',
    'modal.type.subtitle': 'Manage stone classification details.',
    'modal.type.cover_image': 'Cover Image',
    'modal.type.image_url': 'Image URL',
    'modal.type.placeholder_image': 'https://...',
    'modal.type.name': 'Commercial Name',
    'modal.type.placeholder_name': 'e.g. Carrara White',
    'modal.type.origin': 'Origin',
    'modal.type.placeholder_origin': 'e.g. Italy',
    'modal.type.hardness': 'Hardness',
    'modal.type.placeholder_hardness': 'e.g. Mohs 3',
    'modal.type.desc': 'Description',
    'modal.type.placeholder_desc': 'Marketing description...',
    'modal.type.save': 'Save Typology',
    // Interest Thermometer
    'interest.title': 'Interest Heatmap',
    'interest.subtitle': 'Real-time analysis of which lots are attracting the most attention.',
    'interest.level.cold': 'Cold',
    'interest.level.warm': 'Warm',
    'interest.level.hot': 'Hot',
    'interest.tooltip.cold': '0–2 clicks or under 30s total view time with no visits in the last 48h.',
    'interest.tooltip.warm': '3–7 clicks or roughly 30s–2min of total viewing, typically with a recent visit (up to 48h).',
    'interest.tooltip.hot': '8+ clicks or more than 2min of viewing, usually within the last 24h.',
    'interest.table_title': 'Lead Engagement Ranking',
    'interest.search_placeholder': 'Search client or stone...',
    'interest.metrics.views': 'Clicks',
    'interest.metrics.time': 'Time',
    'interest.empty': 'No tracking data available yet.',
    // Modal Indústria
    'modal.ind_inv.direct': 'HQ Link',
    'modal.ind_inv.delegate': 'Delegate',
    'modal.ind_inv.global_inv': 'Inventory Pool',
    'modal.ind_inv.total_batch': 'Batch Total',
    'modal.ind_inv.delegated': 'Delegated',
    'modal.ind_inv.direct_active': 'Direct Active',
    'modal.ind_inv.financials': 'Financial Base',
    'modal.ind_inv.base_cost': 'Ind. Cost',
    'modal.ind_inv.min_price': 'Floor Price',
    'modal.ind_inv.total_value': 'Stock Value',
    'modal.ind_inv.tab.links': 'Links',
    'modal.ind_inv.tab.delegations': 'Partner Access',
    'modal.ind_inv.tab.stock': 'Stock Settings',
    'modal.ind_inv.tab.overview': 'Overview',
    'modal.ind_inv.direct_hq': 'Direct HQ Links',
    'modal.ind_inv.delegated_links': 'Seller Links',
    'modal.ind_inv.generated_by': 'Generated By',
    'modal.ind_inv.no_delegations': 'No partners have access to this lot.',
    'modal.ind_inv.inv_correction': 'Inventory Adjustment',
    'modal.ind_inv.inv_correction_desc': 'Manually adjust the total quantity or prices for this specific batch.',
    'modal.ind_inv.stock_params': 'Global Parameters',
    'modal.ind_inv.min_locked': 'Min. Locked (Sold/Resv)',
    'modal.ind_inv.save_changes': 'Update Batch',
    'modal.ind_inv.assigned': 'Assigned',
    'modal.ind_inv.revoke_remaining': 'Reclaim Stock',
    'modal.ind_inv.remove_access': 'Remove Access',
    'modal.ind_inv.tooltip_active': 'Cannot revoke with active links.',
    // Modal Vendedor
    'modal.seller_inv.redirect_title': 'Transaction Context',
    'modal.seller_inv.redirect_msg': 'Redirecting to detailed activity log for',
    'modal.seller_inv.proceed': 'Proceed to Details',
    'modal.seller_inv.create_new': 'Create New Link',
    'modal.seller_inv.stock_terms': 'Stock Allowance',
    'modal.seller_inv.your_stock': 'Your Allotment',
    'modal.seller_inv.floor_price': 'Industry Floor',
    'modal.seller_inv.terms_desc': 'Prices must stay above the industry floor to ensure your commission.',
    'modal.seller_inv.history_title': 'Your Link Activity',
    'modal.seller_inv.tab.overview': 'Overview',
    'modal.seller_inv.tab.links': 'Links',
    'modal.seller_inv.unit_price': 'Offered Price',
    'modal.seller_inv.est_margin': 'Est. Commission',
    'modal.seller_inv.details': 'Logs',
    'modal.seller_inv.no_links': 'No links generated yet',
    // Modal Batch
    'modal.batch.title': 'Warehouse Entry',
    'modal.batch.subtitle': 'Register new physical material batch into the system.',
    'modal.batch.select_type': 'Material Typology',
    'modal.batch.lot_id': 'Unique Lot ID',
    'modal.batch.regenerate': 'New Code',
    'modal.batch.dim_qty': 'Specs & Quantities',
    'modal.batch.width': 'Width',
    'modal.batch.height': 'Height',
    'modal.batch.thick': 'Thick',
    'modal.batch.unit': 'Unit',
    'modal.batch.qty': 'Total Units',
    'modal.batch.cost_unit': 'Ind. Cost (Unit)',
    'modal.batch.min_unit': 'Floor Price (Unit)',
    'modal.batch.image_opt': 'Lot Image URL',
    'modal.batch.use_catalog': 'Use Standard Photo',
    'modal.batch.save': 'Confirm Entry',
    'modal.batch.placeholder_lot': 'BLK-2024...',
    'modal.batch.placeholder_qty': '0',
    'modal.batch.placeholder_image': 'https://...',
    // Client Page
    'client.industry_name': 'CAVA PREMIUM STONES',
    'client.produced_by': 'Produced & Certified by',
    'client.view_catalog': 'Full Collection',
    'client.nav.secure': 'SECURE PROPOSAL',
    'client.badge.exclusive': 'LIMITED AVAILABILITY',
    'client.origin': 'Origin / Quarry',
    'client.dimensions': 'Exact Dimensions',
    'client.price_unit': 'Unit Price',
    'client.qty_offered': 'Qty. Available',
    'client.btn.reserve': 'Reserve this material',
    'client.validity': 'Exclusive proposal for',
    'client.catalog_title': 'Quarry Collection',
    'client.reserved_badge': 'Exclusively Reserved',
    'client.reserved_for': 'Reserved for',
    'client.reserved_msg': 'This exclusive material is currently held in reservation for your project',
    'client.investment_value': 'Investment Value',
    'client.total_investment': 'Total Investment',
    'client.final_value': 'Final value',
    'client.secured_proposal': 'Secured Proposal',
    'client.valid_for': 'Valid exclusively for',
    'client.active_offer': 'Active Offer',
    'client.per_unit': 'per',
    'client.available': 'available',
    'client.status.active': 'Active',
    'client.status.sold': 'Sold',
    'client.status.expired': 'Expired',
    'client.status.reserved': 'Reserved',
    'client.status.reservation_pending': 'Pending Reservation',
    'client.btn.back': 'Back',
    'client.scroll_down': 'Scroll Down',
    // Roles
    'role.industry': 'Industry',
    'role.seller': 'Seller',
    'role.client': 'Client View',
    // Modals - Cancel & Confirm
    'modal.cancel.title': 'Revoke Access',
    'modal.cancel.msg': 'You are about to cancel the active link for',
    'modal.cancel.bullet1': 'The client will no longer access the page.',
    'modal.cancel.bullet2': 'Reserved inventory will be released immediately.',
    'modal.cancel.undone': 'This action cannot be undone.',
    'modal.cancel.keep': 'Keep Active',
    'modal.cancel.confirm': 'Revoke Link',
    'modal.confirm.title': 'Confirm Sale',
    'modal.confirm.msg': 'You are finalizing the deal with',
    'modal.confirm.item': 'Item',
    'modal.confirm.total_rev': 'Total Revenue',
    'modal.confirm.deduct_msg': 'This will permanently deduct stock from inventory.',
    'modal.confirm.close_msg': 'The transaction will be marked as closed.',
    'modal.confirm.btn': 'Confirm Deal',
    // Direct Link Modal
    'modal.direct.title': 'Generate Direct Link',
    'modal.direct.avail_stock': 'Available Stock',
    'modal.direct.price_unit': 'Unit Price',
    'modal.direct.generate': 'Generate Link',
    // Offer Modal
    'modal.offer.title': 'Create Private Offer',
    'modal.offer.subtitle': 'Generate a secure link for your client.',
    'modal.offer.available': 'Available',
    'modal.offer.qty': 'Quantity',
    'modal.offer.generate_btn': 'Create Proposal',
    // Delegate Modal
    'modal.delegate.title': 'Delegate Stock',
    'modal.delegate.subtitle': 'Assign inventory to a partner seller.',
    'modal.delegate.select_partner': 'Select Partner',
    'modal.delegate.qty_to_delegate': 'Quantity to Delegate',
    'modal.delegate.max': 'Max',
    'modal.delegate.base_cost': 'Base Cost (Locked)',
    'modal.delegate.floor_limit': 'Agreed Floor Price',
    'modal.delegate.confirm': 'Delegate Stock',
    // Notifications
    'notif.title': 'Notifications',
    'notif.mark_all': 'Mark all read',
    'notif.empty': 'No new notifications.',
    // Toasts
    'toast.sale_confirmed': 'Sale confirmed for {client}: {value}',
    'toast.link_cancelled': 'Link for {client} has been revoked.',
    'toast.delegated': 'Stock delegated: {qty} {unit} of {stone}',
    'toast.batch_added': 'Lot {id} successfully registered.',
    'toast.link_ready': 'Private proposal link is now active!',
    'toast.delegation_revoked': 'Delegation revoked and stock reclaimed.',
    'msg.revoke_block_active': 'Cannot revoke: There are active links using this stock.',
    'toast.error_avail': 'Insufficient stock. Only {qty} remaining.',
    'toast.type_updated': 'Typology updated successfully.',
    'toast.type_created': 'New typology registered.'
  },
  pt: {
    // Navegação
    'nav.operations': 'Operações',
    'nav.analytics': 'Analytics',
    'nav.inventory': 'Estoque Ativo',
    'nav.clients': 'Gestão de Clientes',
    'nav.thermometer': 'Termômetro de Interesse',
    'nav.lot_history': 'Histórico de Lotes',
    'nav.dashboard': 'Painel Geral',
    'nav.pipeline': 'Links Ativos',
    'nav.sales': 'Vendas Realizadas',
    'nav.financials_admin': 'Análise de Lucro Líquido',
    'nav.financials_seller': 'Minhas Comissões',
    // CRM
    'cli.title': 'Relacionamento',
    'cli.subtitle': 'Gerencie sua carteira de clientes e acompanhe o engajamento.',
    'cli.add': 'Novo Cliente',
    'cli.search': 'Buscar nome, empresa ou e-mail...',
    'cli.table.client': 'Cliente / Empresa',
    'cli.table.contact': 'Contato',
    'cli.table.offers': 'Links',
    'cli.table.total_purchased': 'Comprado',
    'cli.table.status': 'Engajamento',
    'cli.kpi.total_clients': 'Total Clientes',
    'cli.kpi.active_leads': 'Links Ativos',
    'cli.kpi.conversion': 'Conversão',
    'cli.modal.new': 'Cadastro de Novo Cliente',
    'cli.modal.edit': 'Editar Detalhes',
    'cli.modal.edit_btn': 'Editar Info',
    'cli.label.name': 'Nome Completo',
    'cli.label.company': 'Empresa / Escritório',
    'cli.label.email': 'E-mail',
    'cli.label.phone': 'Telefone',
    'cli.label.notes': 'Notas de Relacionamento',
    'cli.label.no_notes': 'Nenhuma observação registrada.',
    'cli.label.member_since': 'Cliente desde',
    'cli.label.registered_by': 'Cadastrado por',
    'cli.history.title': 'Histórico de Links',
    'cli.history.empty': 'Nenhum link gerado para este cliente.',
    'cli.history.filter_all': 'Todos os Links',
    'cli.history.filter_sold': 'Vendidos',
    'cli.history.filter_active': 'Em Aberto',
    'cli.history.search_placeholder': 'Buscar material ou lote...',
    'cli.history.seller_filter': 'Vendedores',
    'cli.status.hot': 'Link Quente',
    'cli.status.inactive': 'Sem Atividade',
    'cli.select_existing': 'Selecionar do CRM',
    // Dashboard & Analytics
    'dash.title_admin': 'Analytics da Indústria',
    'dash.title_seller': 'Minha Performance',
    'dash.subtitle_admin': 'Visão global das operações em tempo real.',
    'dash.subtitle_seller': 'Acompanhe seus links ativos e comissões.',
    'dash.kpi.pipeline': 'Em Negociação',
    'dash.kpi.pipeline_desc': 'Receita potencial em links ativos',
    'dash.kpi.sold': 'Total Vendido',
    'dash.kpi.sold_desc': 'Receita realizada',
    'dash.kpi.revenue': 'Receita Total',
    'dash.kpi.potential_revenue': 'Receita Possível',
    'dash.kpi.profit': 'Lucro Líquido',
    'dash.kpi.transactions': 'Transações',
    'dash.kpi.volume': 'Volume Total',
    'dash.kpi.units': 'unidades',
    'dash.kpi.reserved_links': 'Links Reservados',
    'dash.kpi.reserved_links_desc': 'Propostas marcadas como reserva',
    'dash.kpi.profit_admin': 'Lucro Líquido',
    'dash.kpi.profit_seller': 'Comissões',
    'dash.kpi.profit_desc': 'Baseado em vendas fechadas',
    'dash.filter.all_sellers': 'Todos Parceiros',
    'dash.status.sold': 'Vendido',
    'dash.status.expired': 'Expirado',
    'dash.status.active': 'Ativo',
    'dash.records_found': 'registros encontrados',
    'dash.recent_transactions': 'Atividade Recente',
    'dash.table.status': 'Status',
    'dash.table.stone': 'Material / Lote',
    'dash.table.client': 'Cliente',
    'dash.table.value': 'Valor',
    'dash.table.actions': 'Ações',
    'dash.table.created': 'Data',
    'dash.table.seller': 'Vendedor',
    'dash.filter.all': 'Todo Período',
    'dash.filter.week': 'Esta Semana',
    'dash.filter.month': 'Este Mês',
    'dash.filter.custom': 'Período Personalizado',
    // Estoque
    'inv.your_inventory': 'Gerencie as chapas e lotes disponíveis.',
    'inv.search_placeholder': 'Buscar lote ou material...',
    'inv.filter.all_types': 'Todas Tipologias',
    'inv.filter.all_status': 'Todos Status',
    'inv.status.available': 'Disponível',
    'inv.status.reserved': 'Reservado',
    'inv.status.sold_out': 'Esgotado',
    'inv.switch.lots': 'Lotes',
    'inv.switch.catalog': 'Catálogo',
    'inv.add_typology': 'Nova Tipologia',
    'inv.history_title': 'Histórico de Lotes',
    'inv.history_subtitle': 'Arquivo de materiais totalmente vendidos e encerrados.',
    'inv.history_empty': 'Ainda não há lotes totalmente vendidos.',
    'inv.add_batch': 'Novo Lote',
    'inv.no_results': 'Nenhum item encontrado.',
    // Cards
    'card.lot': 'Lote',
    'card.floor_price': 'Preço Piso',
    'card.direct_link': 'Link HQ',
    'card.delegate': 'Delegar',
    'card.create_offer': 'Criar Oferta',
    'card.sold': 'Vendido',
    'card.reserved': 'Reservado',
    'card.sent': 'Links Enviados',
    'card.sent_short': 'Enviados',
    'card.avail': 'Disp',
    'card.your_stock': 'Seu Estoque',
    'card.not_in_showroom': 'Não está no seu showroom',
    // Unidades
    'unit.slabs': 'chapas',
    'unit.m2': 'm²',
    // Catálogo
    'cat.no_image': 'Sem Imagem',
    // Comum
    'common.save': 'Salvar Alterações',
    'common.cancel': 'Cancelar',
    'common.search_placeholder': 'Buscar cliente, pedra ou lote...',
    'common.direct_sale': 'Venda Direta',
    'common.select_placeholder': 'Selecione...',
    'analytics.desc': 'Detalhamento financeiro e métricas de links.',
    'analytics.export': 'Exportar CSV',
    // Ações
    'actions.request_reservation': 'Solicitar reserva',
    'actions.reserve_now': 'Reservar agora',
    'actions.approve': 'Aprovar',
    'actions.reject': 'Rejeitar',
    // Modais - Histórico & Status (Global)
    'modal.history.title': 'Histórico de Transações',
    'modal.history.sold': 'Vendido',
    'modal.history.expired': 'Expirado',
    'modal.history.active': 'Ativo',
    'modal.history.copy': 'Copiar Link',
    'modal.history.view': 'Ver Página',
    'modal.history.displaying': 'Exibindo',
    'modal.history.no_links': 'Nenhum link gerado ainda.',
    // Modais - Transações
    'modal.tx.created': 'Criado em',
    'modal.tx.viewed': 'Visualizado',
    'modal.tx.finalized': 'Finalizado',
    'modal.tx.id': 'ID',
    'modal.tx.sold': 'Vendido',
    'modal.tx.active': 'Ativo',
    'modal.tx.unit_price': 'Preço Unitário',
    'modal.tx.qty': 'Quantidade',
    'modal.tx.total_val': 'Valor Total',
    'modal.tx.margin': 'Margem %',
    'modal.tx.est_profit': 'Lucro Est.',
    'modal.tx.est_comm': 'Comissão Est.',
    'modal.tx.timeline': 'Linha do Tempo',
    'modal.tx.open': 'Abrir Link Seguro',
    'modal.tx.cancel': 'Revogar Link',
    'modal.tx.finalize': 'Confirmar Venda',
    // Modais - Tipologia
    'modal.type.edit_title': 'Editar Tipologia',
    'modal.type.new_title': 'Nova Tipologia',
    'modal.type.subtitle': 'Gerencie detalhes de classificação da rocha.',
    'modal.type.cover_image': 'Imagem de Capa',
    'modal.type.image_url': 'URL da Imagem',
    'modal.type.placeholder_image': 'https://...',
    'modal.type.name': 'Nome Comercial',
    'modal.type.placeholder_name': 'Ex: Branco Carrara',
    'modal.type.origin': 'Origem',
    'modal.type.placeholder_origin': 'Ex: Itália',
    'modal.type.hardness': 'Dureza',
    'modal.type.placeholder_hardness': 'Ex: Mohs 3',
    'modal.type.desc': 'Descrição',
    'modal.type.placeholder_desc': 'Descrição de marketing...',
    'modal.type.save': 'Salvar Tipologia',
    // Termômetro
    'interest.title': 'Calor do Mercado',
    'interest.subtitle': 'Análise em tempo real de quais lotes estão atraindo mais atenção.',
    'interest.level.cold': 'Frio',
    'interest.level.warm': 'Morno',
    'interest.level.hot': 'Quente',
    'interest.tooltip.cold': '0–2 cliques ou menos de 30s somados, sem visitas nas últimas 48h.',
    'interest.tooltip.warm': '3–7 cliques ou ~30s–2min de visualização, com acesso recente (até 48h).',
    'interest.tooltip.hot': '8+ cliques ou mais de 2min de visualização, normalmente nas últimas 24h.',
    'interest.table_title': 'Ranking de Engajamento de Leads',
    'interest.search_placeholder': 'Buscar cliente ou pedra...',
    'interest.metrics.views': 'Cliques',
    'interest.metrics.time': 'Tempo',
    'interest.empty': 'Sem dados de rastreamento disponíveis.',
    // Modal Indústria
    'modal.ind_inv.direct': 'Link Direto',
    'modal.ind_inv.delegate': 'Delegar',
    'modal.ind_inv.global_inv': 'Resumo de Estoque',
    'modal.ind_inv.total_batch': 'Total do Lote',
    'modal.ind_inv.delegated': 'Delegado',
    'modal.ind_inv.direct_active': 'Venda Direta Ativa',
    'modal.ind_inv.financials': 'Base Financeira',
    'modal.ind_inv.base_cost': 'Custo Ind.',
    'modal.ind_inv.min_price': 'Preço Piso',
    'modal.ind_inv.total_value': 'Valor em Estoque',
    'modal.ind_inv.tab.links': 'Links',
    'modal.ind_inv.tab.delegations': 'Acesso de Parceiros',
    'modal.ind_inv.tab.stock': 'Config. Estoque',
    'modal.ind_inv.tab.overview': 'Visão Geral',
    'modal.ind_inv.direct_hq': 'Links Diretos HQ',
    'modal.ind_inv.delegated_links': 'Links de Vendedores',
    'modal.ind_inv.generated_by': 'Gerado Por',
    'modal.ind_inv.no_delegations': 'Nenhum parceiro tem acesso a este lote.',
    'modal.ind_inv.inv_correction': 'Ajuste de Inventário',
    'modal.ind_inv.inv_correction_desc': 'Ajuste manualmente a quantidade total ou preços para este lote específico.',
    'modal.ind_inv.stock_params': 'Parâmetros Globais',
    'modal.ind_inv.min_locked': 'Mín. Travado (Vendido/Resv)',
    'modal.ind_inv.save_changes': 'Atualizar Lote',
    'modal.ind_inv.assigned': 'Atribuído',
    'modal.ind_inv.revoke_remaining': 'Retomar Estoque',
    'modal.ind_inv.remove_access': 'Remover Acesso',
    'modal.ind_inv.tooltip_active': 'Não é possível revogar com links ativos.',
    // Modal Vendedor
    'modal.seller_inv.redirect_title': 'Contexto da Transação',
    'modal.seller_inv.redirect_msg': 'Redirecionando para o log detalhado de atividade de',
    'modal.seller_inv.proceed': 'Ir para Detalhes',
    'modal.seller_inv.create_new': 'Criar Novo Link',
    'modal.seller_inv.stock_terms': 'Permissão de Estoque',
    'modal.seller_inv.your_stock': 'Sua Cota',
    'modal.seller_inv.floor_price': 'Piso da Indústria',
    'modal.seller_inv.terms_desc': 'Os preços devem permanecer acima do piso para garantir sua comissão.',
    'modal.seller_inv.history_title': 'Atividade dos seus Links',
    'modal.seller_inv.tab.overview': 'Visão Geral',
    'modal.seller_inv.tab.links': 'Links',
    'modal.seller_inv.unit_price': 'Preço Ofertado',
    'modal.seller_inv.est_margin': 'Comissão Est.',
    'modal.seller_inv.details': 'Logs',
    'modal.seller_inv.no_links': 'Nenhum link gerado ainda',
    // Modal Batch
    'modal.batch.title': 'Entrada de Armazém',
    'modal.batch.subtitle': 'Registrar novo lote de material físico no sistema.',
    'modal.batch.select_type': 'Tipologia do Material',
    'modal.batch.lot_id': 'ID Único do Lote',
    'modal.batch.regenerate': 'Novo Código',
    'modal.batch.dim_qty': 'Medidas e Quantidades',
    'modal.batch.width': 'Largura',
    'modal.batch.height': 'Altura',
    'modal.batch.thick': 'Espessura',
    'modal.batch.unit': 'Unidade',
    'modal.batch.qty': 'Total Unidades',
    'modal.batch.cost_unit': 'Custo Ind. (Un)',
    'modal.batch.min_unit': 'Preço Piso (Un)',
    'modal.batch.image_opt': 'URL da Imagem do Lote',
    'modal.batch.use_catalog': 'Usar Foto Padrão',
    'modal.batch.save': 'Confirmar Entrada',
    'modal.batch.placeholder_lot': 'BLK-2024...',
    'modal.batch.placeholder_qty': '0',
    'modal.batch.placeholder_image': 'https://...',
    // Página Cliente
    'client.industry_name': 'CAVA ROCHAS PREMIUM',
    'client.produced_by': 'Produzido e Certificado por',
    'client.view_catalog': 'Coleção Completa',
    'client.nav.secure': 'PROPOSTA SEGURA',
    'client.badge.exclusive': 'DISPONIBILIDADE LIMITADA',
    'client.origin': 'Origem / Pedreira',
    'client.dimensions': 'Medidas Exatas',
    'client.price_unit': 'Preço Unitário',
    'client.qty_offered': 'Qtd. Disponível',
    'client.btn.reserve': 'Reservar este material',
    'client.validity': 'Proposta exclusiva para',
    'client.catalog_title': 'Coleção da Pedreira',
    'client.reserved_badge': 'Exclusivamente Reservado',
    'client.reserved_for': 'Reservado para',
    'client.reserved_msg': 'Este material exclusivo está atualmente reservado para o seu projeto',
    'client.investment_value': 'Valor do Investimento',
    'client.total_investment': 'Investimento Total',
    'client.final_value': 'Valor final',
    'client.secured_proposal': 'Proposta Garantida',
    'client.valid_for': 'Válido exclusivamente para',
    'client.active_offer': 'Oferta Ativa',
    'client.per_unit': 'por',
    'client.available': 'disponível',
    'client.status.active': 'Ativo',
    'client.status.sold': 'Vendido',
    'client.status.expired': 'Expirado',
    'client.status.reserved': 'Reservado',
    'client.status.reservation_pending': 'Reserva Pendente',
    'client.btn.back': 'Voltar',
    'client.scroll_down': 'Desça para Ver Mais',
    // Roles
    'role.industry': 'Indústria',
    'role.seller': 'Vendedor',
    'role.client': 'Visão Cliente',
    // Modals - Cancelar & Confirmar
    'modal.cancel.title': 'Revogar Acesso',
    'modal.cancel.msg': 'Você está prestes a cancelar o link ativo para',
    'modal.cancel.bullet1': 'O cliente não terá mais acesso à página.',
    'modal.cancel.bullet2': 'O estoque reservado será liberado imediatamente.',
    'modal.cancel.undone': 'Esta ação não pode ser desfeita.',
    'modal.cancel.keep': 'Manter Ativo',
    'modal.cancel.confirm': 'Revogar Link',
    'modal.confirm.title': 'Confirmar Venda',
    'modal.confirm.msg': 'Você está finalizando a negociação com',
    'modal.confirm.item': 'Item',
    'modal.confirm.total_rev': 'Receita Total',
    'modal.confirm.deduct_msg': 'Isso deduzirá permanentemente do estoque.',
    'modal.confirm.close_msg': 'A transação será marcada como encerrada.',
    'modal.confirm.btn': 'Confirmar Negócio',
    // Modal Link Direto
    'modal.direct.title': 'Gerar Link Direto',
    'modal.direct.avail_stock': 'Estoque Disponível',
    'modal.direct.price_unit': 'Preço Unitário',
    'modal.direct.generate': 'Gerar Link',
    // Modal Oferta
    'modal.offer.title': 'Criar Oferta Privada',
    'modal.offer.subtitle': 'Gere um link seguro para seu cliente.',
    'modal.offer.available': 'Disponível',
    'modal.offer.qty': 'Quantidade',
    'modal.offer.generate_btn': 'Criar Proposta',
    // Modal Delegar
    'modal.delegate.title': 'Delegar Estoque',
    'modal.delegate.subtitle': 'Atribua inventário a um vendedor parceiro.',
    'modal.delegate.select_partner': 'Selecionar Parceiro',
    'modal.delegate.qty_to_delegate': 'Qtd. para Delegar',
    'modal.delegate.max': 'Máx',
    'modal.delegate.base_cost': 'Custo Base (Travado)',
    'modal.delegate.floor_limit': 'Preço Piso Acordado',
    'modal.delegate.confirm': 'Delegar Estoque',
    // Notificações
    'notif.title': 'Notificações',
    'notif.mark_all': 'Marcar todas lidas',
    'notif.empty': 'Nenhuma nova notificação.',
    // Toasts
    'toast.sale_confirmed': 'Venda confirmada para {client}: {value}',
    'toast.link_cancelled': 'O link para {client} foi revogado.',
    'toast.delegated': 'Estoque delegado: {qty} {unit} de {stone}',
    'toast.batch_added': 'Lote {id} registrado com sucesso.',
    'toast.link_ready': 'O link da proposta já está ativo!',
    'toast.delegation_revoked': 'Delegação revogada e estoque retomado.',
    'msg.revoke_block_active': 'Não é possível revogar: Existem links ativos usando este estoque.',
    'toast.error_avail': 'Estoque insuficiente. Apenas {qty} restantes.',
    'toast.type_updated': 'Tipologia atualizada com sucesso.',
    'toast.type_created': 'Nova tipologia registrada.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const getInitialLanguage = (): Language => {
    const browserLang = navigator.language || (navigator as any).userLanguage || 'en';
    return browserLang.startsWith('pt') ? 'pt' : 'en';
  };

  const [language, setLanguage] = useState<Language>(getInitialLanguage());

  const locale = useMemo(() => language === 'pt' ? 'pt-BR' : 'en-US', [language]);
  const currency = useMemo(() => language === 'pt' ? 'BRL' : 'USD', [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  const formatDate = (date: string | Date, options?: Intl.DateTimeFormatOptions) => {
    const defaultOptions: Intl.DateTimeFormatOptions = options || {
      day: '2-digit',
      month: 'short',
      year: '2-digit'
    };
    return new Date(date).toLocaleDateString(locale, defaultOptions);
  };

  const formatDateTime = (date: string | Date) => {
    return new Date(date).toLocaleString(locale, {
      day: '2-digit',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency: currency,
    }).format(value);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatDate, formatDateTime, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
