import React, { createContext, useContext, useState, ReactNode, useMemo } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  formatDate: (date: string | Date, options?: Intl.DateTimeFormatOptions) => string;
  formatDateTime: (date: string | Date) => string;
  formatCurrency: (value: number) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'role.industry': 'Industry Admin',
    'role.seller': 'Seller View',
    'role.client': 'Client View',
    'header.welcome': 'Welcome back,',
    'header.notifications': 'Notifications',
    'header.demo': 'Demo Controls',
    'nav.operations': 'Operations',
    'nav.inventory': 'Inventory & Catalog',
    'nav.lot_history': 'Lot History',
    'nav.analytics': 'Analytics & Performance',
    'nav.dashboard': 'Overview Dashboard',
    'nav.pipeline': 'Active Links',
    'nav.sales': 'Sales History',
    'nav.financials_admin': 'Net Profit Analysis',
    'nav.financials_seller': 'Commissions',
    'dash.title_admin': 'Industry Analytics',
    'dash.title_seller': 'Sales Performance',
    'dash.subtitle_admin': 'Real-time overview of global operations.',
    'dash.subtitle_seller': 'Track your active links and potential commissions.',
    'dash.kpi.pipeline': 'Active Links',
    'dash.kpi.pipeline_desc': 'Potential revenue from active links',
    'dash.kpi.sold': 'Total Sold',
    'dash.kpi.sold_desc': 'Realized revenue',
    'dash.kpi.revenue': 'Total Revenue',
    'dash.kpi.potential_revenue': 'Potential Revenue',
    'dash.kpi.profit': 'Net Profit',
    'dash.kpi.transactions': 'Transactions',
    'dash.kpi.volume': 'Total Volume',
    'dash.kpi.units': 'units',
    'dash.kpi.profit_admin': 'Net Profit (Realized)',
    'dash.kpi.profit_seller': 'Commission (Realized)',
    'dash.kpi.profit_desc': 'Based on realized sales',
    'dash.recent_transactions': 'Recent Transactions & Links',
    'dash.filter.period': 'Period:',
    'dash.filter.all': 'All',
    'dash.filter.today': 'Today',
    'dash.filter.week': 'Week',
    'dash.filter.month': 'Month',
    'dash.filter.year': 'Year',
    'dash.filter.custom': 'Custom',
    'dash.table.status': 'Status',
    'dash.table.created': 'Created',
    'dash.table.stone': 'Stone / Lot',
    'dash.table.seller': 'Seller',
    'dash.table.client': 'Client Ref',
    'dash.table.value': 'Value',
    'dash.table.expires': 'Expires',
    'dash.table.actions': 'Actions',
    'dash.status.sold': 'Sold',
    'dash.status.expired': 'Expired',
    'dash.status.active': 'Active',
    'dash.records_found': 'records found',
    'dash.filter_by': 'Filter:',
    'dash.filter.all_sellers': 'All Sellers',
    'dash.no_tx': 'No transactions found for this period.',
    'analytics.export': 'Export Report',
    'analytics.desc': 'Detailed breakdown and analysis of transactions.',
    'inv.tab.stock': 'Stock & Inventory',
    'inv.tab.catalog': 'Typology Catalog',
    'inv.physical_stock': 'Physical Stock',
    'inv.add_batch': 'Add New Batch',
    'inv.your_inventory': 'Your Inventory',
    'inv.no_stones': 'No stones assigned to you yet.',
    'inv.no_results': 'No stones found matching your filters.',
    'inv.history_empty': 'No lots have been fully sold yet.',
    'inv.search_placeholder': 'Search by Lot ID, Name...',
    'inv.filter.all_types': 'All Typologies',
    'inv.filter.all_status': 'All Status',
    'inv.status.available': 'Available Stock',
    'inv.status.reserved': 'Reserved/Delegated',
    'inv.status.sold_out': 'Sold Out',
    'inv.history_title': 'Completed Lots History',
    'inv.history_subtitle': 'Archive of blocks and batches fully sold and closed.',
    'cat.title': 'Product Catalog',
    'cat.subtitle': 'Manage stone templates and technical specifications.',
    'cat.add_btn': 'Add New Typology',
    'cat.no_image': 'No Image',
    'card.lot': 'Lot',
    'card.floor_price': 'Floor Price',
    'card.direct_link': 'Direct Link',
    'card.delegate': 'Delegate',
    'card.your_stock': 'Your Stock',
    'card.create_offer': 'Create Offer',
    'card.links': 'Links',
    'card.not_in_showroom': 'Not currently in your showroom',
    'card.sold': 'Sold',
    'card.reserved': 'Reserved',
    'card.avail': 'Avail',
    'notif.title': 'Notifications',
    'notif.mark_all': 'Mark all read',
    'notif.empty': 'No notifications yet.',
    'toast.link_ready': 'Link Ready!',
    'toast.copied': 'Copied to clipboard!',
    'toast.dismiss': 'Dismiss',
    'toast.copy': 'Copy',
    'toast.view': 'View',
    'unit.slabs': 'slabs',
    'unit.m2': 'm²',
    'common.select_placeholder': '-- Select --',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.clear': 'Clear',
    'common.search_placeholder': 'Search Client, Stone, Lot or Seller...',
    'common.direct_sale': 'Direct Sale',
    'modal.ind_inv.direct': 'Direct link',
    'modal.ind_inv.delegate': 'Delegate',
    'modal.ind_inv.global_inv': 'Global Inventory',
    'modal.ind_inv.total_batch': 'Total Batch',
    'modal.ind_inv.financials': 'Financials',
    'modal.ind_inv.base_cost': 'Base Cost',
    'modal.ind_inv.min_price': 'Min Price',
    'modal.ind_inv.total_value': 'Total Batch Value (Min)',
    'modal.ind_inv.tab.links': 'Global Offer Links',
    'modal.ind_inv.tab.delegations': 'Active Delegations',
    'modal.ind_inv.tab.stock': 'Stock Management',
    'modal.ind_inv.direct_hq': 'Direct Links',
    'modal.ind_inv.delegated_links': 'Seller Links',
    'modal.ind_inv.generated_by': 'Generated By',
    'modal.ind_inv.assigned': 'Assigned',
    'modal.ind_inv.inv_correction': 'Inventory Correction',
    'modal.ind_inv.inv_correction_desc': 'Update total physical quantities and financial parameters. Changes here directly affect available stock and profit calculations.',
    'modal.ind_inv.save_changes': 'Save Changes',
    'modal.ind_inv.stock_params': 'Physical Stock Parameters',
    'modal.ind_inv.min_locked': 'Minimum Locked by Active/Sold',
    'modal.ind_inv.no_delegations': 'No active delegations. All stock is controlled by HQ.',
    'modal.seller_inv.redirect_title': 'Redirect to Active Links?',
    'modal.seller_inv.redirect_msg': 'You are leaving the inventory view to manage the transaction details for',
    'modal.seller_inv.proceed': 'Proceed',
    'modal.seller_inv.your_stock': 'Your Stock',
    'modal.seller_inv.floor_price': 'Floor Price',
    'modal.seller_inv.create_new': 'Create New Link',
    'modal.seller_inv.history_title': 'Generated Links History',
    'modal.seller_inv.no_links': 'No links generated yet.',
    'modal.seller_inv.unit_price': 'Unit Price',
    'modal.seller_inv.est_margin': 'Est. Margin',
    'modal.seller_inv.details': 'Details',
    'modal.seller_inv.stock_terms': 'Stock & Terms',
    'modal.seller_inv.terms_desc': 'You can generate links with prices above the floor price. The difference is your commission.',
    'modal.tx.id': 'Transaction ID',
    'modal.tx.sold': 'Sold',
    'modal.tx.expired': 'Expired',
    'modal.tx.active': 'Active',
    'modal.tx.unit_price': 'Unit Price',
    'modal.tx.qty': 'Quantity',
    'modal.tx.total_val': 'Total Value',
    'modal.tx.margin': 'Margin',
    'modal.tx.timeline': 'Activity Timeline',
    'modal.tx.created': 'Offer Created',
    'modal.tx.viewed': 'Link Accessed',
    'modal.tx.finalized': 'Sale Finalized',
    'modal.tx.expiry': 'Expiration',
    'modal.tx.copy': 'Copy Link',
    'modal.tx.open': 'Open Page',
    'modal.tx.cancel': 'Cancel Link',
    'modal.tx.finalize': 'Finalize Sale',
    'modal.delegate.title': 'Delegate Inventory',
    'modal.delegate.subtitle': 'Assign quantity to sales partner',
    'modal.delegate.select_partner': 'Select Partner',
    'modal.delegate.qty_to_delegate': 'Quantity to Delegate',
    'modal.delegate.max': 'Max',
    'modal.delegate.base_cost': 'Base Cost',
    'modal.delegate.floor_limit': 'Floor Price Limit',
    'modal.delegate.confirm': 'Confirm Delegation',
    'modal.offer.title': 'Create Private Offer',
    'modal.offer.subtitle': 'Configure pricing and client details.',
    'modal.offer.sale_price': 'Sale Price (Total)',
    'modal.offer.floor': 'Floor',
    'modal.offer.potential_comm': 'Potential Commission',
    'modal.offer.qty': 'Quantity',
    'modal.offer.available': 'Available',
    'modal.offer.client_ref': 'Client Ref',
    'modal.offer.placeholder_client': 'Client Name or Reference',
    'modal.offer.generate_btn': 'Generate Secure Link',
    'modal.offer.generating': 'Generating...',
    'modal.direct.title': 'Direct Sales Link',
    'modal.direct.avail_stock': 'Available Stock',
    'modal.direct.price_unit': 'Final Price per Unit',
    'modal.direct.client_ref': 'Client Reference',
    'modal.direct.placeholder_client': 'e.g. VIP Client',
    'modal.direct.valid_days': 'Valid For (Days)',
    'modal.direct.generate': 'Generate Link',
    'modal.history.title': 'Offer History',
    'modal.history.no_links': 'No links created for this stone yet.',
    'modal.history.active': 'Active',
    'modal.history.expired': 'Expired',
    'modal.history.sold': 'Sold',
    'modal.history.copy': 'Copy',
    'modal.history.view': 'View',
    'modal.history.displaying': 'Displaying',
    'modal.type.edit_title': 'Edit Stone Typology',
    'modal.type.new_title': 'New Stone Typology',
    'modal.type.subtitle': 'Define catalog template.',
    'modal.type.cover_image': 'Cover Image',
    'modal.type.image_url': 'Image URL',
    'modal.type.placeholder_image': 'https://...',
    'modal.type.name': 'Name',
    'modal.type.placeholder_name': 'e.g. Premium White Marble',
    'modal.type.origin': 'Origin',
    'modal.type.placeholder_origin': 'e.g. Italy',
    'modal.type.hardness': 'Hardness',
    'modal.type.placeholder_hardness': 'e.g. Mohs 4',
    'modal.type.desc': 'Description',
    'modal.type.placeholder_desc': 'Detailed technical description...',
    'modal.type.save': 'Save Typology',
    'modal.batch.title': 'New Inventory Entry',
    'modal.batch.subtitle': 'Register physical material (Batch/Block).',
    'modal.batch.select_type': 'Select Catalog Item',
    'modal.batch.lot_id': 'Lot / Block ID',
    'modal.batch.placeholder_lot': 'Select stone to generate ID...',
    'modal.batch.regenerate': 'REGENERATE',
    'modal.batch.dim_qty': 'Dimensions & Quantity',
    'modal.batch.width': 'Width',
    'modal.batch.height': 'Height',
    'modal.batch.thick': 'Thickness',
    'modal.batch.unit': 'Unit',
    'modal.batch.qty': 'Quantity',
    'modal.batch.placeholder_qty': 'Total slabs',
    'modal.batch.financials': 'Financial Parameters',
    'modal.batch.cost_unit': 'Base Cost (Per Unit)',
    'modal.batch.min_unit': 'Min Price (Per Unit)',
    'modal.batch.image_opt': 'Batch Image URL (Optional)',
    'modal.batch.placeholder_image': 'https://... (Blank for Catalog image)',
    'modal.batch.use_catalog': 'Use Catalog Image',
    'modal.batch.save': 'Save Batch Entry',
    'modal.cancel.title': 'Cancel Active Link?',
    'modal.cancel.msg': 'You are about to cancel the link for',
    'modal.cancel.bullet1': 'The client will lose access.',
    'modal.cancel.bullet2': 'Stock will be released immediately.',
    'modal.cancel.undone': 'Action cannot be undone.',
    'modal.cancel.keep': 'Keep Active',
    'modal.cancel.confirm': 'Yes, Cancel Link',
    'modal.confirm.title': 'Confirm Final Sale?',
    'modal.confirm.msg': 'Finalize transaction with',
    'modal.confirm.item': 'Item',
    'modal.confirm.total_rev': 'Total Revenue',
    'modal.confirm.deduct_msg': 'Inventory will be permanently deducted.',
    'modal.confirm.close_msg': 'Deal will be marked as closed.',
    'modal.confirm.btn': 'Confirm Sale',
    'client.nav.secure': 'Secure Offer View',
    'client.badge.exclusive': 'Exclusive Offer',
    'client.dimensions': 'Dimensions',
    'client.origin': 'Origin',
    'client.price_unit': 'Price per Unit',
    'client.qty_offered': 'Quantity Offered',
    'client.total_value': 'Total Value',
    'client.btn.reserve': 'Reserve Now',
    'client.contact': 'Questions? Contact',
    'client.validity': 'This offer is valid for',
    'client.until': 'until',
  },
  pt: {
    'role.industry': 'Admin Indústria',
    'role.seller': 'Visão Vendedor',
    'role.client': 'Visão Cliente',
    'header.welcome': 'Bem-vindo de volta,',
    'header.notifications': 'Notificações',
    'header.demo': 'Controles Demo',
    'nav.operations': 'Operações',
    'nav.inventory': 'Estoque & Catálogo',
    'nav.lot_history': 'Histórico de Lotes',
    'nav.analytics': 'Análises & Performance',
    'nav.dashboard': 'Painel Geral',
    'nav.pipeline': 'Links Ativos',
    'nav.sales': 'Histórico de Vendas',
    'nav.financials_admin': 'Análise de Lucro Líquido',
    'nav.financials_seller': 'Comissões',
    'dash.title_admin': 'Analytics da Indústria',
    'dash.title_seller': 'Performance de Vendas',
    'dash.subtitle_admin': 'Visão em tempo real das operações globais.',
    'dash.subtitle_seller': 'Acompanhe seus links ativos e comissões potenciais.',
    'dash.kpi.pipeline': 'Links Ativos',
    'dash.kpi.pipeline_desc': 'Receita potencial de links ativos',
    'dash.kpi.sold': 'Total Vendido',
    'dash.kpi.sold_desc': 'Receita realizada',
    'dash.kpi.revenue': 'Receita Total',
    'dash.kpi.potential_revenue': 'Possível Receita',
    'dash.kpi.profit': 'Lucro Líquido',
    'dash.kpi.transactions': 'Transações',
    'dash.kpi.volume': 'Volume Total',
    'dash.kpi.units': 'unidades',
    'dash.kpi.profit_admin': 'Lucro Líquido (Realizado)',
    'dash.kpi.profit_seller': 'Comissão (Realizada)',
    'dash.kpi.profit_desc': 'Baseado em vendas concretizadas',
    'dash.recent_transactions': 'Transações Recentes & Links',
    'dash.filter.period': 'Período:',
    'dash.filter.all': 'Tudo',
    'dash.filter.today': 'Hoje',
    'dash.filter.week': 'Semana',
    'dash.filter.month': 'Mês',
    'dash.filter.year': 'Ano',
    'dash.filter.custom': 'Personalizado',
    'dash.table.status': 'Status',
    'dash.table.created': 'Criado em',
    'dash.table.stone': 'Pedra / Lote',
    'dash.table.seller': 'Vendedor',
    'dash.table.client': 'Ref. Cliente',
    'dash.table.value': 'Valor',
    'dash.table.expires': 'Expira em',
    'dash.table.actions': 'Ações',
    'dash.status.sold': 'Vendido',
    'dash.status.expired': 'Expirado',
    'dash.status.active': 'Ativo',
    'dash.records_found': 'registros encontrados',
    'dash.filter_by': 'Filtro:',
    'dash.filter.all_sellers': 'Todos Vendedores',
    'dash.no_tx': 'Nenhuma transação encontrada para este período.',
    'analytics.export': 'Exportar Relatório',
    'analytics.desc': 'Detalhamento e análise de transações.',
    'inv.tab.stock': 'Estoque Ativo',
    'inv.tab.catalog': 'Catálogo de Tipologias',
    'inv.physical_stock': 'Estoque Ativo',
    'inv.add_batch': 'Adicionar Lote',
    'inv.your_inventory': 'Seu Inventário',
    'inv.no_stones': 'Nenhuma pedra atribuída a você ainda.',
    'inv.no_results': 'Nenhuma pedra encontrada com estes filtros.',
    'inv.history_empty': 'Ainda não há lotes totalmente vendidos.',
    'inv.search_placeholder': 'Buscar por Lote, Nome...',
    'inv.filter.all_types': 'Todas Tipologias',
    'inv.filter.all_status': 'Todos Status',
    'inv.status.available': 'Estoque Disponível',
    'inv.status.reserved': 'Reservado/Delegado',
    'inv.status.sold_out': 'Esgotado',
    'inv.history_title': 'Histórico de Lotes Concluídos',
    'inv.history_subtitle': 'Arquivo de blocos e lotes totalmente vendidos e encerrados.',
    'cat.title': 'Catálogo de Produtos',
    'cat.subtitle': 'Gerencie modelos de pedras e especificações técnicas.',
    'cat.add_btn': 'Nova Tipologia',
    'cat.no_image': 'Sem Imagem',
    'card.lot': 'Lote',
    'card.floor_price': 'Preço Piso',
    'card.direct_link': 'Link Direto',
    'card.delegate': 'Delegar',
    'card.your_stock': 'Seu Estoque',
    'card.create_offer': 'Criar Oferta',
    'card.links': 'Links',
    'card.not_in_showroom': 'Não está no seu showroom',
    'card.sold': 'Vend',
    'card.reserved': 'Resv',
    'card.avail': 'Disp',
    'notif.title': 'Notificações',
    'notif.mark_all': 'Marcar todas como lidas',
    'notif.empty': 'Nenhuma notificação ainda.',
    'toast.link_ready': 'Link Pronto!',
    'toast.copied': 'Copiado para área de transferência!',
    'toast.dismiss': 'Fechar',
    'toast.copy': 'Copiar',
    'toast.view': 'Ver',
    'unit.slabs': 'chapas',
    'unit.m2': 'm²',
    'common.select_placeholder': '-- Selecione --',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.clear': 'Limpar',
    'common.search_placeholder': 'Buscar Cliente, Pedra, Lote ou Vendedor...',
    'common.direct_sale': 'Venda Direta',
    'modal.ind_inv.direct': 'Link direto',
    'modal.ind_inv.delegate': 'Delegar',
    'modal.ind_inv.global_inv': 'Inventário Global',
    'modal.ind_inv.total_batch': 'Lote Total',
    'modal.ind_inv.financials': 'Financeiro',
    'modal.ind_inv.base_cost': 'Custo Base',
    'modal.ind_inv.min_price': 'Preço Mín',
    'modal.ind_inv.total_value': 'Valor Total do Lote (Mín)',
    'modal.ind_inv.tab.links': 'Links de Oferta Globais',
    'modal.ind_inv.tab.delegations': 'Delegações Ativas',
    'modal.ind_inv.tab.stock': 'Gestão de Estoque',
    'modal.ind_inv.direct_hq': 'Links Diretos',
    'modal.ind_inv.delegated_links': 'Links de Vendedores',
    'modal.ind_inv.generated_by': 'Gerado Por',
    'modal.ind_inv.assigned': 'Atribuído',
    'modal.ind_inv.inv_correction': 'Correção de Inventário',
    'modal.ind_inv.inv_correction_desc': 'Atualize as quantidades físicas totais e parâmetros financeiros. Alterações aqui afetam diretamente o estoque disponível e cálculos de lucro.',
    'modal.ind_inv.save_changes': 'Salvar Alterações',
    'modal.ind_inv.stock_params': 'Parâmetros de Estoque Físico',
    'modal.ind_inv.min_locked': 'Mínimo travado por Ativos/Vendidos',
    'modal.ind_inv.no_delegations': 'Nenhuma delegação ativa. Todo o estoque é controlado pela HQ.',
    'modal.seller_inv.redirect_title': 'Redirecionar para Links Ativos?',
    'modal.seller_inv.redirect_msg': 'Você está saindo da visão de inventário para gerenciar os detalhes da transação para',
    'modal.seller_inv.proceed': 'Prosseguir',
    'modal.seller_inv.your_stock': 'Seu Estoque',
    'modal.seller_inv.floor_price': 'Preço Piso',
    'modal.seller_inv.create_new': 'Criar Novo Link',
    'modal.seller_inv.history_title': 'Histórico de Links Gerados',
    'modal.seller_inv.no_links': 'Nenhum link gerado ainda.',
    'modal.seller_inv.unit_price': 'Preço Unit.',
    'modal.seller_inv.est_margin': 'Margem Est.',
    'modal.seller_inv.details': 'Detalhes',
    'modal.seller_inv.stock_terms': 'Estoque & Termos',
    'modal.seller_inv.terms_desc': 'Você pode gerar links com preços acima do preço piso. A diferença é sua comissão.',
    'modal.tx.id': 'ID da Transação',
    'modal.tx.sold': 'Vendido',
    'modal.tx.expired': 'Expirado',
    'modal.tx.active': 'Ativo',
    'modal.tx.unit_price': 'Preço Unit.',
    'modal.tx.qty': 'Quantidade',
    'modal.tx.total_val': 'Valor Total',
    'modal.tx.margin': 'Margem',
    'modal.tx.timeline': 'Linha do Tempo',
    'modal.tx.created': 'Oferta Criada',
    'modal.tx.viewed': 'Link Acessado',
    'modal.tx.finalized': 'Venda Finalizada',
    'modal.tx.expiry': 'Expiração',
    'modal.tx.copy': 'Copiar Link',
    'modal.tx.open': 'Abrir Página',
    'modal.tx.cancel': 'Cancelar Link',
    'modal.tx.finalize': 'Finalizar Venda',
    'modal.delegate.title': 'Delegar Estoque',
    'modal.delegate.subtitle': 'Atribuir quantidade ao parceiro de vendas',
    'modal.delegate.select_partner': 'Selecionar Parceiro',
    'modal.delegate.qty_to_delegate': 'Qtd. para Delegar',
    'modal.delegate.max': 'Max',
    'modal.delegate.base_cost': 'Custo Base',
    'modal.delegate.floor_limit': 'Limite de Preço Piso',
    'modal.delegate.confirm': 'Confirmar Delegação',
    'modal.offer.title': 'Criar Oferta Privada',
    'modal.offer.subtitle': 'Configure preços e detalhes do cliente.',
    'modal.offer.sale_price': 'Preço de Venda (Total)',
    'modal.offer.floor': 'Piso',
    'modal.offer.potential_comm': 'Comissão Potencial',
    'modal.offer.qty': 'Quantidade',
    'modal.offer.available': 'Disponível',
    'modal.offer.client_ref': 'Ref. Cliente',
    'modal.offer.placeholder_client': 'Nome do Cliente ou Referência',
    'modal.offer.generate_btn': 'Gerar Link Seguro',
    'modal.offer.generating': 'Gerando...',
    'modal.direct.title': 'Link de Venda Direta',
    'modal.direct.avail_stock': 'Estoque Disponível',
    'modal.direct.price_unit': 'Preço Final por Unidade',
    'modal.direct.client_ref': 'Referência do Cliente',
    'modal.direct.placeholder_client': 'ex: Cliente VIP',
    'modal.direct.valid_days': 'Válido por (Dias)',
    'modal.direct.generate': 'Gerar Link',
    'modal.history.title': 'Histórico de Ofertas',
    'modal.history.no_links': 'Nenhum link criado para esta pedra ainda.',
    'modal.history.active': 'Ativo',
    'modal.history.expired': 'Expirado',
    'modal.history.sold': 'Sold',
    'modal.history.copy': 'Copiar',
    'modal.history.view': 'Ver',
    'modal.history.displaying': 'Exibindo',
    'modal.type.edit_title': 'Editar Tipologia',
    'modal.type.new_title': 'Nova Tipologia',
    'modal.type.subtitle': 'Defina o modelo de catálogo.',
    'modal.type.cover_image': 'Imagem de Capa',
    'modal.type.image_url': 'URL da Imagem',
    'modal.type.placeholder_image': 'https://...',
    'modal.type.name': 'Nome',
    'modal.type.placeholder_name': 'ex: Granito Preto Absoluto',
    'modal.type.origin': 'Origem',
    'modal.type.placeholder_origin': 'ex: Brasil',
    'modal.type.hardness': 'Dureza',
    'modal.type.placeholder_hardness': 'ex: Mohs 7',
    'modal.type.desc': 'Descrição',
    'modal.type.placeholder_desc': 'Descrição técnica detalhada...',
    'modal.type.save': 'Salvar Tipologia',
    'modal.batch.title': 'Nova Entrada de Estoque',
    'modal.batch.subtitle': 'Registrar chegada de material (Lote/Bloco).',
    'modal.batch.select_type': 'Selecionar Item do Catálogo',
    'modal.batch.lot_id': 'ID do Lote / Bloco',
    'modal.batch.placeholder_lot': 'Selecione a pedra para gerar ID...',
    'modal.batch.regenerate': 'REGERAR',
    'modal.batch.dim_qty': 'Dimensões & Quantidade',
    'modal.batch.width': 'Largura',
    'modal.batch.height': 'Altura',
    'modal.batch.thick': 'Espessura',
    'modal.batch.unit': 'Unidade',
    'modal.batch.qty': 'Quantidade',
    'modal.batch.placeholder_qty': 'Total de chapas',
    'modal.batch.financials': 'Parâmetros Financeiros',
    'modal.batch.cost_unit': 'Custo Base (Por Unid.)',
    'modal.batch.min_unit': 'Preço Mín/Piso (Por Unid.)',
    'modal.batch.image_opt': 'URL Imagem (Opcional)',
    'modal.batch.placeholder_image': 'https://... (Vazio para imagem do catálogo)',
    'modal.batch.use_catalog': 'Usar Imagem do Catálogo',
    'modal.batch.save': 'Salvar Entrada',
    'modal.cancel.title': 'Cancelar Link Ativo?',
    'modal.cancel.msg': 'Você está prestes a cancelar o link para',
    'modal.cancel.bullet1': 'O cliente perderá o acesso.',
    'modal.cancel.bullet2': 'O estoque será liberado imediatamente.',
    'modal.cancel.undone': 'Esta ação não pode ser desfeita.',
    'modal.cancel.keep': 'Manter Ativo',
    'modal.cancel.confirm': 'Sim, Cancelar Link',
    'modal.confirm.title': 'Confirmar Venda Final?',
    'modal.confirm.msg': 'Finalizar transação com',
    'modal.confirm.item': 'Item',
    'modal.confirm.total_rev': 'Receita Total',
    'modal.confirm.deduct_msg': 'O estoque será deduzido permanentemente.',
    'modal.confirm.close_msg': 'O negócio será marcado como fechado.',
    'modal.confirm.btn': 'Confirmar Venda',
    'client.nav.secure': 'Visualização Segura de Oferta',
    'client.badge.exclusive': 'Oferta Exclusiva',
    'client.dimensions': 'Dimensões',
    'client.origin': 'Origem',
    'client.price_unit': 'Preço por Unidade',
    'client.qty_offered': 'Qtd. Ofertada',
    'client.total_value': 'Valor Total',
    'client.btn.reserve': 'Reservar Agora',
    'client.contact': 'Dúvidas? Contate',
    'client.validity': 'Esta oferta é válida para',
    'client.until': 'até',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const getInitialLanguage = (): Language => {
    const browserLang = navigator.language || (navigator as any).userLanguage || 'en';
    return browserLang.startsWith('pt') ? 'pt' : 'en';
  };

  const [language, setLanguage] = useState<Language>(getInitialLanguage());

  const locale = useMemo(() => language === 'pt' ? 'pt-BR' : 'en-US', [language]);
  const currency = useMemo(() => language === 'pt' ? 'BRL' : 'USD', [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const formatDate = (date: string | Date, options?: Intl.DateTimeFormatOptions): string => {
    const defaultOptions: Intl.DateTimeFormatOptions = options || { 
      day: '2-digit', 
      month: 'short', 
      year: '2-digit' 
    };
    return new Date(date).toLocaleDateString(locale, defaultOptions);
  };

  const formatDateTime = (date: string | Date): string => {
    return new Date(date).toLocaleString(locale, {
      day: '2-digit',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const formatCurrency = (value: number): string => {
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency: currency,
    }).format(value);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatDate, formatDateTime, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
